# Generated by Django 5.2.5 on 2025-08-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL amigable')),
                ('page_type', models.CharField(choices=[('home', 'Página Principal'), ('properties', 'Catálogo de Propiedades'), ('about', 'Acerca de'), ('contact', 'Contacto'), ('custom', 'Personalizada')], max_length=20, verbose_name='Tipo de página')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='¿Es página principal?')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('condo', 'Condominio'), ('townhouse', 'Casa adosada'), ('land', 'Terreno'), ('commercial', 'Comercial')], max_length=20, verbose_name='Tipo de propiedad')),
                ('sale_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler'), ('both', 'Venta y Alquiler')], default='sale', max_length=10, verbose_name='Tipo de venta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('price_currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m²)')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Espacios de estacionamiento')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page', verbose_name='Página')),
                ('property_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.property', verbose_name='Propiedad de interés')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('properties_grid', 'Galería de Propiedades'), ('contact_form', 'Formulario de Contacto'), ('text_content', 'Contenido de Texto'), ('image_gallery', 'Galería de Imágenes'), ('footer', 'Footer')], max_length=20, verbose_name='Tipo de sección')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('hero_button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón')),
                ('hero_button_link', models.CharField(blank=True, max_length=200, verbose_name='Enlace del botón')),
                ('background_image', models.ImageField(blank=True, upload_to='sections/', verbose_name='Imagen de fondo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['order'],
            },
        ),
    ]
