# Generated by Django 5.2.5 on 2025-08-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/', verbose_name='Archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de medio')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño del archivo (bytes)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
                'ordering': ['-created_at'],
            },
        ),
    ]
