# Generated by Django 5.2.5 on 2025-08-23 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tenant')),
                ('subdomain', models.CharField(help_text='Subdominio para acceder al tenant (ej: cliente1)', max_length=50, unique=True, verbose_name='Subdominio')),
                ('domain', models.CharField(blank=True, help_text='Dominio personalizado opcional', max_length=255, null=True, verbose_name='Dominio personalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Es dueño')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario del Tenant',
                'verbose_name_plural': 'Usuarios del Tenant',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
